const FontSizes = {
  FONT_SIZE_TERMS: 10,
  FONT_SIZE_EXTRA_SMALL: 12,
  FONT_SIZE_SMALL: 14,
  FONT_SIZE_DEFAULT: 16,
  FONT_SIZE_MEDIUM: 18,
  FONT_SIZE_EXTRA_MEDIUM: 20,
  FONT_SIZE_LARGE: 22,
  FONT_SIZE_XL: 24,
  FONT_SIZE_XXL: 26,
  FONT_SIZE_XXXL: 28,
  FONT_SIZE_SUPREME: 30,
};

export default FontSizes;
